collections:
  - name: ansible.posix
  - name: community.general
  - name: community.postgresql
  - name: vyos.vyos
  - name: cisco.ios
  - name: fortinet.fortios
  - name: ansible.windows
  - name: community.windows
  - name: community.network
